/*
   +----------------------------------------------------------------------+
   | PHP Version 7                                                        |
   +----------------------------------------------------------------------+
   | Copyright (c) The PHP Group                                          |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
   | Author: Guillaume Amringer                                           |
   +----------------------------------------------------------------------+
*/

#include "pkcs11int.h"


void general_error(char *generic, char *specific) {
    char buf[256];
    sprintf(buf, "%s: %s", generic, specific);
    zend_throw_exception(zend_ce_exception, buf, 0);
}

void pkcs11_error(CK_RV rv, char *error) {
    char buf[256];
    sprintf(buf, "(0x%08lx) PKCS#11 module error: %s", rv, error);
    zend_throw_exception(zend_ce_exception, buf, 0);
}

void parseTemplate(HashTable **template, CK_ATTRIBUTE_PTR *templateObj, int *templateItemCount) {
    zval *templateValue;
    zend_ulong templateValueKey;
    *templateItemCount = zend_hash_num_elements(*template);
    *templateObj = ecalloc(*templateItemCount, sizeof(CK_ATTRIBUTE));
    unsigned int i = 0;
    static CK_BBOOL btrue = CK_TRUE;
    static CK_BBOOL bfalse = CK_FALSE;
    ZEND_HASH_FOREACH_NUM_KEY_VAL(*template, templateValueKey, templateValue)
        if (Z_TYPE_P(templateValue) == IS_LONG) {
            (*templateObj)[i] = (CK_ATTRIBUTE){templateValueKey, &(Z_LVAL_P(templateValue)), sizeof(CK_ULONG)};

        } else if (Z_TYPE_P(templateValue) == IS_STRING) {
            (*templateObj)[i] = (CK_ATTRIBUTE){templateValueKey, Z_STRVAL_P(templateValue), Z_STRLEN_P(templateValue)};

        } else if (Z_TYPE_P(templateValue) == IS_TRUE) {
            (*templateObj)[i] = (CK_ATTRIBUTE){templateValueKey, &btrue, sizeof(btrue)};

        } else if (Z_TYPE_P(templateValue) == IS_FALSE) {
            (*templateObj)[i] = (CK_ATTRIBUTE){templateValueKey, &bfalse, sizeof(bfalse)};

        } else {
            general_error("Unable to parse template", "Unsupported parameter type");
        }

        i++;
    ZEND_HASH_FOREACH_END();
}

void freeTemplate(CK_ATTRIBUTE_PTR templateObj) {
    efree(templateObj);
}

void getObjectClass(pkcs11_session_object *session, CK_OBJECT_HANDLE_PTR hObject, CK_ULONG_PTR classId) {
    CK_ATTRIBUTE template[] = {
        {CKA_CLASS, NULL_PTR, 0}
    };
    CK_RV rv;
    
    rv = session->pkcs11->functionList->C_GetAttributeValue(
        session->session,
        *hObject,
        template,
        1
    );
    if (rv != CKR_OK) {
        pkcs11_error(rv, "Unable to get attribute value");
        return;
    }
    template[0].pValue = (uint8_t *) ecalloc(1, template[0].ulValueLen);

    rv = session->pkcs11->functionList->C_GetAttributeValue(
        session->session,
        *hObject,
        template,
        1
    );
    if (rv != CKR_OK) {
        pkcs11_error(rv, "Unable to get attribute value");
        return;
    }

    memcpy(
        classId,
        template[0].pValue,
        template[0].ulValueLen
    );

    efree(template[0].pValue);
}


PHP_MINIT_FUNCTION(pkcs11)
{
    register_pkcs11();
    register_pkcs11_session();
    register_pkcs11_object();
    register_pkcs11_key();
    register_pkcs11_keypair();
    register_pkcs11_mechanism();
    register_pkcs11_rsapssparams();
    register_pkcs11_rsaoaepparams();
    register_pkcs11_gcmparams();
    register_pkcs11_chacha20params();
    register_pkcs11_salsa20params();
    register_pkcs11_salsa20chacha20poly1305params();
    register_pkcs11_ecdh1deriveparams();
    register_pkcs11_signaturecontext();
    register_pkcs11_verificationcontext();
    register_pkcs11_digestcontext();
    register_pkcs11_encryptioncontext();
    register_pkcs11_decryptioncontext();

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_PKCS_KEY_PAIR_GEN",      0x00000000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_PKCS",                   0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_9796",                   0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_X_509",                  0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD2_RSA_PKCS",               0x00000004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD5_RSA_PKCS",               0x00000005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA1_RSA_PKCS",              0x00000006UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD128_RSA_PKCS",         0x00000007UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD160_RSA_PKCS",         0x00000008UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_PKCS_OAEP",              0x00000009UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_X9_31_KEY_PAIR_GEN",     0x0000000AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_X9_31",                  0x0000000BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA1_RSA_X9_31",             0x0000000CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_PKCS_PSS",               0x0000000DUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA1_RSA_PKCS_PSS",          0x0000000EUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_KEY_PAIR_GEN",           0x00000010UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA",                        0x00000011UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA1",                   0x00000012UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA224",                 0x00000013UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA256",                 0x00000014UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA384",                 0x00000015UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA512",                 0x00000016UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA3_224",               0x00000018UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA3_256",               0x00000019UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA3_384",               0x0000001AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHA3_512",               0x0000001BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DH_PKCS_KEY_PAIR_GEN",       0x00000020UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DH_PKCS_DERIVE",             0x00000021UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X9_42_DH_KEY_PAIR_GEN",      0x00000030UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X9_42_DH_DERIVE",            0x00000031UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X9_42_DH_HYBRID_DERIVE",     0x00000032UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X9_42_MQV_DERIVE",           0x00000033UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA256_RSA_PKCS",            0x00000040UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA384_RSA_PKCS",            0x00000041UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_RSA_PKCS",            0x00000042UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA256_RSA_PKCS_PSS",        0x00000043UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA384_RSA_PKCS_PSS",        0x00000044UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_RSA_PKCS_PSS",        0x00000045UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA224_RSA_PKCS",            0x00000046UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA224_RSA_PKCS_PSS",        0x00000047UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_224",                 0x00000048UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_224_HMAC",            0x00000049UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_224_HMAC_GENERAL",    0x0000004AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_224_KEY_DERIVATION",  0x0000004BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_256",                 0x0000004CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_256_HMAC",            0x0000004DUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_256_HMAC_GENERAL",    0x0000004EUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_256_KEY_DERIVATION",  0x0000004FUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_T",                   0x00000050UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_T_HMAC",              0x00000051UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_T_HMAC_GENERAL",      0x00000052UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_T_KEY_DERIVATION",    0x00000053UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256_RSA_PKCS",          0x00000060UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384_RSA_PKCS",          0x00000061UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512_RSA_PKCS",          0x00000062UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256_RSA_PKCS_PSS",      0x00000063UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384_RSA_PKCS_PSS",      0x00000064UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512_RSA_PKCS_PSS",      0x00000065UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224_RSA_PKCS",          0x00000066UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224_RSA_PKCS_PSS",      0x00000067UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC2_KEY_GEN",                0x00000100UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC2_ECB",                    0x00000101UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC2_CBC",                    0x00000102UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC2_MAC",                    0x00000103UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC2_MAC_GENERAL",            0x00000104UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC2_CBC_PAD",                0x00000105UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC4_KEY_GEN",                0x00000110UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC4",                        0x00000111UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_KEY_GEN",                0x00000120UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_ECB",                    0x00000121UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_CBC",                    0x00000122UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_MAC",                    0x00000123UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_MAC_GENERAL",            0x00000124UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_CBC_PAD",                0x00000125UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES2_KEY_GEN",               0x00000130UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_KEY_GEN",               0x00000131UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_ECB",                   0x00000132UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_CBC",                   0x00000133UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_MAC",                   0x00000134UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_MAC_GENERAL",           0x00000135UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_CBC_PAD",               0x00000136UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_CMAC_GENERAL",          0x00000137UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_CMAC",                  0x00000138UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CDMF_KEY_GEN",               0x00000140UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CDMF_ECB",                   0x00000141UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CDMF_CBC",                   0x00000142UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CDMF_MAC",                   0x00000143UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CDMF_MAC_GENERAL",           0x00000144UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CDMF_CBC_PAD",               0x00000145UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_OFB64",                  0x00000150UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_OFB8",                   0x00000151UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_CFB64",                  0x00000152UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_CFB8",                   0x00000153UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD2",                        0x00000200UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD2_HMAC",                   0x00000201UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD2_HMAC_GENERAL",           0x00000202UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD5",                        0x00000210UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD5_HMAC",                   0x00000211UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD5_HMAC_GENERAL",           0x00000212UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA_1",                      0x00000220UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA_1_HMAC",                 0x00000221UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA_1_HMAC_GENERAL",         0x00000222UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD128",                  0x00000230UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD128_HMAC",             0x00000231UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD128_HMAC_GENERAL",     0x00000232UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD160",                  0x00000240UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD160_HMAC",             0x00000241UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RIPEMD160_HMAC_GENERAL",     0x00000242UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA256",                     0x00000250UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA256_HMAC",                0x00000251UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA256_HMAC_GENERAL",        0x00000252UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA224",                     0x00000255UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA224_HMAC",                0x00000256UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA224_HMAC_GENERAL",        0x00000257UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA384",                     0x00000260UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA384_HMAC",                0x00000261UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA384_HMAC_GENERAL",        0x00000262UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512",                     0x00000270UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_HMAC",                0x00000271UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_HMAC_GENERAL",        0x00000272UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SECURID_KEY_GEN",            0x00000280UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SECURID",                    0x00000282UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_HOTP_KEY_GEN",               0x00000290UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_HOTP",                       0x00000291UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ACTI",                       0x000002A0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ACTI_KEY_GEN",               0x000002A1UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256",                   0x000002B0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256_HMAC",              0x000002B1UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256_HMAC_GENERAL",      0x000002B2UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256_KEY_GEN",           0x000002B3UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224",                   0x000002B5UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224_HMAC",              0x000002B6UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224_HMAC_GENERAL",      0x000002B7UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224_KEY_GEN",           0x000002B8UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384",                   0x000002C0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384_HMAC",              0x000002C1UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384_HMAC_GENERAL",      0x000002C2UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384_KEY_GEN",           0x000002C3UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512",                   0x000002D0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512_HMAC",              0x000002D1UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512_HMAC_GENERAL",      0x000002D2UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512_KEY_GEN",           0x000002D3UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST_KEY_GEN",               0x00000300UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST_ECB",                   0x00000301UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST_CBC",                   0x00000302UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST_MAC",                   0x00000303UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST_MAC_GENERAL",           0x00000304UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST_CBC_PAD",               0x00000305UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST3_KEY_GEN",              0x00000310UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST3_ECB",                  0x00000311UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST3_CBC",                  0x00000312UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST3_MAC",                  0x00000313UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST3_MAC_GENERAL",          0x00000314UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST3_CBC_PAD",              0x00000315UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST5_KEY_GEN",              0x00000320UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST128_KEY_GEN",            0x00000320UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST5_ECB",                  0x00000321UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST128_ECB",                0x00000321UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST5_CBC",                  0x00000322UL , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST128_CBC",                0x00000322UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST5_MAC",                  0x00000323UL , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST128_MAC",                0x00000323UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST5_MAC_GENERAL",          0x00000324UL , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST128_MAC_GENERAL",        0x00000324UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST5_CBC_PAD",              0x00000325UL , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAST128_CBC_PAD",            0x00000325UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC5_KEY_GEN",                0x00000330UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC5_ECB",                    0x00000331UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC5_CBC",                    0x00000332UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC5_MAC",                    0x00000333UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC5_MAC_GENERAL",            0x00000334UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RC5_CBC_PAD",                0x00000335UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_IDEA_KEY_GEN",               0x00000340UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_IDEA_ECB",                   0x00000341UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_IDEA_CBC",                   0x00000342UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_IDEA_MAC",                   0x00000343UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_IDEA_MAC_GENERAL",           0x00000344UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_IDEA_CBC_PAD",               0x00000345UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GENERIC_SECRET_KEY_GEN",     0x00000350UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CONCATENATE_BASE_AND_KEY",   0x00000360UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CONCATENATE_BASE_AND_DATA",  0x00000362UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CONCATENATE_DATA_AND_BASE",  0x00000363UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_XOR_BASE_AND_DATA",          0x00000364UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_EXTRACT_KEY_FROM_KEY",       0x00000365UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SSL3_PRE_MASTER_KEY_GEN",    0x00000370UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SSL3_MASTER_KEY_DERIVE",     0x00000371UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SSL3_KEY_AND_MAC_DERIVE",    0x00000372UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SSL3_MASTER_KEY_DERIVE_DH",  0x00000373UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS_PRE_MASTER_KEY_GEN",     0x00000374UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS_MASTER_KEY_DERIVE",      0x00000375UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS_KEY_AND_MAC_DERIVE",     0x00000376UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS_MASTER_KEY_DERIVE_DH",   0x00000377UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS_PRF",                    0x00000378UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SSL3_MD5_MAC",               0x00000380UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SSL3_SHA1_MAC",              0x00000381UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD5_KEY_DERIVATION",         0x00000390UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_MD2_KEY_DERIVATION",         0x00000391UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA1_KEY_DERIVATION",        0x00000392UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA256_KEY_DERIVATION",      0x00000393UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA384_KEY_DERIVATION",      0x00000394UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_KEY_DERIVATION",      0x00000395UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA224_KEY_DERIVATION",      0x00000396UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256_KEY_DERIVATION",    0x00000397UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224_KEY_DERIVATION",    0x00000398UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384_KEY_DERIVATION",    0x00000399UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512_KEY_DERIVATION",    0x0000039AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHAKE_128_KEY_DERIVATION",   0x0000039BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHAKE_256_KEY_DERIVATION",   0x0000039CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_256_KEY_DERIVE",        0x00000397UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_224_KEY_DERIVE",        0x00000398UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_384_KEY_DERIVE",        0x00000399UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA3_512_KEY_DERIVE",        0x0000039AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHAKE_128_KEY_DERIVE",       0x0000039BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHAKE_256_KEY_DERIVE",       0x0000039CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_MD2_DES_CBC",            0x000003A0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_MD5_DES_CBC",            0x000003A1UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_MD5_CAST_CBC",           0x000003A2UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_MD5_CAST3_CBC",          0x000003A3UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_MD5_CAST5_CBC",          0x000003A4UL , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_MD5_CAST128_CBC",        0x000003A4UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_CAST5_CBC",         0x000003A5UL , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_CAST128_CBC",       0x000003A5UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_RC4_128",           0x000003A6UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_RC4_40",            0x000003A7UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_DES3_EDE_CBC",      0x000003A8UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_DES2_EDE_CBC",      0x000003A9UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_RC2_128_CBC",       0x000003AAUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBE_SHA1_RC2_40_CBC",        0x000003ABUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PKCS5_PBKD2",                0x000003B0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_PBA_SHA1_WITH_SHA1_HMAC",    0x000003C0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_WTLS_PRE_MASTER_KEY_GEN",         0x000003D0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_WTLS_MASTER_KEY_DERIVE",          0x000003D1UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC",   0x000003D2UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_WTLS_PRF",                        0x000003D3UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE",  0x000003D4UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE",  0x000003D5UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS12_MAC",                       0x000003D8UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS12_KDF",                       0x000003D9UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS12_MASTER_KEY_DERIVE",         0x000003E0UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS12_KEY_AND_MAC_DERIVE",        0x000003E1UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS12_MASTER_KEY_DERIVE_DH",      0x000003E2UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS12_KEY_SAFE_DERIVE",           0x000003E3UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS_MAC",                         0x000003E4UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TLS_KDF",                         0x000003E5UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KEY_WRAP_LYNKS",             0x00000400UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KEY_WRAP_SET_OAEP",          0x00000401UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CMS_SIG",                    0x00000500UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KIP_DERIVE",                 0x00000510UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KIP_WRAP",                   0x00000511UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KIP_MAC",                    0x00000512UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_KEY_GEN",           0x00000550UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_ECB",               0x00000551UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_CBC",               0x00000552UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_MAC",               0x00000553UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_MAC_GENERAL",       0x00000554UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_CBC_PAD",           0x00000555UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_ECB_ENCRYPT_DATA",  0x00000556UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_CBC_ENCRYPT_DATA",  0x00000557UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CAMELLIA_CTR",               0x00000558UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_KEY_GEN",               0x00000560UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_ECB",                   0x00000561UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_CBC",                   0x00000562UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_MAC",                   0x00000563UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_MAC_GENERAL",           0x00000564UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_CBC_PAD",               0x00000565UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_ECB_ENCRYPT_DATA",      0x00000566UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ARIA_CBC_ENCRYPT_DATA",      0x00000567UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_KEY_GEN",               0x00000650UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_ECB",                   0x00000651UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_CBC",                   0x00000652UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_MAC",                   0x00000653UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_MAC_GENERAL",           0x00000654UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_CBC_PAD",               0x00000655UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_ECB_ENCRYPT_DATA",      0x00000656UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SEED_CBC_ENCRYPT_DATA",      0x00000657UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_KEY_GEN",           0x00001000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_ECB64",             0x00001001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_CBC64",             0x00001002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_OFB64",             0x00001003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_CFB64",             0x00001004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_CFB32",             0x00001005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_CFB16",             0x00001006UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_CFB8",              0x00001007UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_WRAP",              0x00001008UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_PRIVATE_WRAP",      0x00001009UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SKIPJACK_RELAYX",            0x0000100aUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KEA_KEY_PAIR_GEN",           0x00001010UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KEA_KEY_DERIVE",             0x00001011UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_KEA_DERIVE",                 0x00001012UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_FORTEZZA_TIMESTAMP",         0x00001020UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BATON_KEY_GEN",              0x00001030UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BATON_ECB128",               0x00001031UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BATON_ECB96",                0x00001032UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BATON_CBC128",               0x00001033UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BATON_COUNTER",              0x00001034UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BATON_SHUFFLE",              0x00001035UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BATON_WRAP",                 0x00001036UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_KEY_PAIR_GEN",         0x00001040UL , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_EC_KEY_PAIR_GEN",            0x00001040UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA",                      0x00001041UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA1",                 0x00001042UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA224",               0x00001043UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA256",               0x00001044UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA384",               0x00001045UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA512",               0x00001046UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_EC_KEY_PAIR_GEN_W_EXTRA_BITS", 0x0000140BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDH1_DERIVE",               0x00001050UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDH1_COFACTOR_DERIVE",      0x00001051UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECMQV_DERIVE",               0x00001052UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDH_AES_KEY_WRAP",          0x00001053UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_AES_KEY_WRAP",           0x00001054UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_JUNIPER_KEY_GEN",            0x00001060UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_JUNIPER_ECB128",             0x00001061UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_JUNIPER_CBC128",             0x00001062UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_JUNIPER_COUNTER",            0x00001063UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_JUNIPER_SHUFFLE",            0x00001064UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_JUNIPER_WRAP",               0x00001065UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_FASTHASH",                   0x00001070UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_XTS",                    0x00001071UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_XTS_KEY_GEN",            0x00001072UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_KEY_GEN",                0x00001080UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_ECB",                    0x00001081UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CBC",                    0x00001082UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_MAC",                    0x00001083UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_MAC_GENERAL",            0x00001084UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CBC_PAD",                0x00001085UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CTR",                    0x00001086UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_GCM",                    0x00001087UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CCM",                    0x00001088UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CTS",                    0x00001089UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CMAC",                   0x0000108AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CMAC_GENERAL",           0x0000108BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_XCBC_MAC",               0x0000108CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_XCBC_MAC_96",            0x0000108DUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_GMAC",                   0x0000108EUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLOWFISH_KEY_GEN",           0x00001090UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLOWFISH_CBC",               0x00001091UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TWOFISH_KEY_GEN",            0x00001092UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TWOFISH_CBC",                0x00001093UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLOWFISH_CBC_PAD",           0x00001094UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_TWOFISH_CBC_PAD",            0x00001095UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_ECB_ENCRYPT_DATA",       0x00001100UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES_CBC_ENCRYPT_DATA",       0x00001101UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_ECB_ENCRYPT_DATA",      0x00001102UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DES3_CBC_ENCRYPT_DATA",      0x00001103UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_ECB_ENCRYPT_DATA",       0x00001104UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CBC_ENCRYPT_DATA",       0x00001105UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOSTR3410_KEY_PAIR_GEN",     0x00001200UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOSTR3410",                  0x00001201UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOSTR3410_WITH_GOSTR3411",   0x00001202UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOSTR3410_KEY_WRAP",         0x00001203UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOSTR3410_DERIVE",           0x00001204UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOSTR3411",                  0x00001210UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOSTR3411_HMAC",             0x00001211UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOST28147_KEY_GEN",          0x00001220UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOST28147_ECB",              0x00001221UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOST28147",                  0x00001222UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOST28147_MAC",              0x00001223UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_GOST28147_KEY_WRAP",         0x00001224UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CHACHA20_KEY_GEN",           0x00001225UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CHACHA20",                   0x00001226UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_POLY1305_KEY_GEN",           0x00001227UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_POLY1305",                   0x00001228UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_PARAMETER_GEN",          0x00002000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DH_PKCS_PARAMETER_GEN",      0x00002001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X9_42_DH_PARAMETER_GEN",     0x00002002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_PROBABILISTIC_PARAMETER_GEN",   0x00002003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_PROBABLISTIC_PARAMETER_GEN",    0x00002003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN",    0x00002004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_DSA_FIPS_G_GEN",             0x00002005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_OFB",                    0x00002104UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CFB64",                  0x00002105UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CFB8",                   0x00002106UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CFB128",                 0x00002107UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_CFB1",                   0x00002108UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_KEY_WRAP",               0x00002109UL     , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_KEY_WRAP_PAD",           0x0000210AUL     , CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_AES_KEY_WRAP_KWP",           0x0000210BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_PKCS_TPM_1_1",           0x00004001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_RSA_PKCS_OAEP_TPM_1_1",      0x00004002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA_1_KEY_GEN",              0x00004003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA224_KEY_GEN",             0x00004004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA256_KEY_GEN",             0x00004005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA384_KEY_GEN",             0x00004006UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_KEY_GEN",             0x00004007UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_224_KEY_GEN",         0x00004008UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_256_KEY_GEN",         0x00004009UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SHA512_T_KEY_GEN",           0x0000400aUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_NULL",                       0x0000400bUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_160",                0x0000400cUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_160_HMAC",           0x0000400dUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_160_HMAC_GENERAL",   0x0000400eUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_160_KEY_DERIVE",     0x0000400fUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_160_KEY_GEN",        0x00004010UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_256",                0x00004011UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_256_HMAC",           0x00004012UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_256_HMAC_GENERAL",   0x00004013UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_256_KEY_DERIVE",     0x00004014UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_256_KEY_GEN",        0x00004015UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_384",                0x00004016UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_384_HMAC",           0x00004017UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_384_HMAC_GENERAL",   0x00004018UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_384_KEY_DERIVE",     0x00004019UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_384_KEY_GEN",        0x0000401aUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_512",                0x0000401bUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_512_HMAC",           0x0000401cUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_512_HMAC_GENERAL",   0x0000401dUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_512_KEY_DERIVE",     0x0000401eUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_BLAKE2B_512_KEY_GEN",        0x0000401fUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SALSA20",                    0x00004020UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_CHACHA20_POLY1305",          0x00004021UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SALSA20_POLY1305",           0x00004022UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X3DH_INITIALIZE",            0x00004023UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X3DH_RESPOND",               0x00004024UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X2RATCHET_INITIALIZE",       0x00004025UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X2RATCHET_RESPOND",          0x00004026UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X2RATCHET_ENCRYPT",          0x00004027UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_X2RATCHET_DECRYPT",          0x00004028UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_XEDDSA",                     0x00004029UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_HKDF_DERIVE",                0x0000402aUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_HKDF_DATA",                  0x0000402bUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_HKDF_KEY_GEN",               0x0000402cUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SALSA20_KEY_GEN",            0x0000402dUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA3_224",             0x00001047UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA3_256",             0x00001048UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA3_384",             0x00001049UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_ECDSA_SHA3_512",             0x0000104aUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_EC_EDWARDS_KEY_PAIR_GEN",    0x00001055UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_EC_MONTGOMERY_KEY_PAIR_GEN", 0x00001056UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_EDDSA",                      0x00001057UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SP800_108_COUNTER_KDF",      0x000003acUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SP800_108_FEEDBACK_KDF",     0x000003adUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_SP800_108_DOUBLE_PIPELINE_KDF", 0x000003aeUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKM_VENDOR_DEFINED",             0x80000000UL, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKF_RW_SESSION",                 0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKF_SERIAL_SESSION",             0x00000004UL, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKU_SO",                         0x00000000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKU_USER",                       0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKU_CONTEXT_SPECIFIC",           0x00000002UL, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKS_RO_PUBLIC_SESSION",          0x00000000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKS_RO_USER_FUNCTIONS",          0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKS_RW_PUBLIC_SESSION",          0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKS_RW_USER_FUNCTIONS",          0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKS_RW_SO_FUNCTIONS",            0x00000004UL, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_CLASS",                      0x00000000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_TOKEN",                      0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PRIVATE",                    0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_LABEL",                      0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_APPLICATION",                0x00000010UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_VALUE",                      0x00000011UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OBJECT_ID",                  0x00000012UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_CERTIFICATE_TYPE",           0x00000080UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ISSUER",                     0x00000081UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SERIAL_NUMBER",              0x00000082UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_AC_ISSUER",                  0x00000083UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OWNER",                      0x00000084UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ATTR_TYPES",                 0x00000085UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_TRUSTED",                    0x00000086UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_CERTIFICATE_CATEGORY",       0x00000087UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_JAVA_MIDP_SECURITY_DOMAIN",  0x00000088UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_URL",                        0x00000089UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_HASH_OF_SUBJECT_PUBLIC_KEY", 0x0000008AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_HASH_OF_ISSUER_PUBLIC_KEY",  0x0000008BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_NAME_HASH_ALGORITHM",        0x0000008CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_CHECK_VALUE",                0x00000090UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_KEY_TYPE",                   0x00000100UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SUBJECT",                    0x00000101UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ID",                         0x00000102UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SENSITIVE",                  0x00000103UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ENCRYPT",                    0x00000104UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_DECRYPT",                    0x00000105UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_WRAP",                       0x00000106UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_UNWRAP",                     0x00000107UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SIGN",                       0x00000108UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SIGN_RECOVER",               0x00000109UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_VERIFY",                     0x0000010AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_VERIFY_RECOVER",             0x0000010BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_DERIVE",                     0x0000010CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_START_DATE",                 0x00000110UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_END_DATE",                   0x00000111UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_MODULUS",                    0x00000120UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_MODULUS_BITS",               0x00000121UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PUBLIC_EXPONENT",            0x00000122UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PRIVATE_EXPONENT",           0x00000123UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PRIME_1",                    0x00000124UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PRIME_2",                    0x00000125UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_EXPONENT_1",                 0x00000126UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_EXPONENT_2",                 0x00000127UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_COEFFICIENT",                0x00000128UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PUBLIC_KEY_INFO",            0x00000129UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PRIME",                      0x00000130UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SUBPRIME",                   0x00000131UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_BASE",                       0x00000132UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PRIME_BITS",                 0x00000133UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SUBPRIME_BITS",              0x00000134UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SUB_PRIME_BITS",             CKA_SUBPRIME_BITS, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_VALUE_BITS",                 0x00000160UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_VALUE_LEN",                  0x00000161UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_EXTRACTABLE",                0x00000162UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_LOCAL",                      0x00000163UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_NEVER_EXTRACTABLE",          0x00000164UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ALWAYS_SENSITIVE",           0x00000165UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_KEY_GEN_MECHANISM",          0x00000166UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_MODIFIABLE",                 0x00000170UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_COPYABLE",                   0x00000171UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_DESTROYABLE",                0x00000172UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ECDSA_PARAMS",               0x00000180UL /* Deprecated */, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_EC_PARAMS",                  0x00000180UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_EC_POINT",                   0x00000181UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SECONDARY_AUTH",             0x00000200UL /* Deprecated */, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_AUTH_PIN_FLAGS",             0x00000201UL /* Deprecated */, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ALWAYS_AUTHENTICATE",        0x00000202UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_WRAP_WITH_TRUSTED",          0x00000210UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_WRAP_TEMPLATE",              (CKF_ARRAY_ATTRIBUTE|0x00000211UL), CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_UNWRAP_TEMPLATE",            (CKF_ARRAY_ATTRIBUTE|0x00000212UL), CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_DERIVE_TEMPLATE",            (CKF_ARRAY_ATTRIBUTE|0x00000213UL), CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_FORMAT",                 0x00000220UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_LENGTH",                 0x00000221UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_TIME_INTERVAL",          0x00000222UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_USER_FRIENDLY_MODE",     0x00000223UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_CHALLENGE_REQUIREMENT",  0x00000224UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_TIME_REQUIREMENT",       0x00000225UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_COUNTER_REQUIREMENT",    0x00000226UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_PIN_REQUIREMENT",        0x00000227UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_COUNTER",                0x0000022EUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_TIME",                   0x0000022FUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_USER_IDENTIFIER",        0x0000022AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_SERVICE_IDENTIFIER",     0x0000022BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_SERVICE_LOGO",           0x0000022CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_OTP_SERVICE_LOGO_TYPE",      0x0000022DUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_GOSTR3410_PARAMS",           0x00000250UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_GOSTR3411_PARAMS",           0x00000251UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_GOST28147_PARAMS",           0x00000252UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_HW_FEATURE_TYPE",            0x00000300UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_RESET_ON_INIT",              0x00000301UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_HAS_RESET",                  0x00000302UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PIXEL_X",                    0x00000400UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PIXEL_Y",                    0x00000401UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_RESOLUTION",                 0x00000402UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_CHAR_ROWS",                  0x00000403UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_CHAR_COLUMNS",               0x00000404UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_COLOR",                      0x00000405UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_BITS_PER_PIXEL",             0x00000406UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_CHAR_SETS",                  0x00000480UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ENCODING_METHODS",           0x00000481UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_MIME_TYPES",                 0x00000482UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_MECHANISM_TYPE",             0x00000500UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_REQUIRED_CMS_ATTRIBUTES",    0x00000501UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_DEFAULT_CMS_ATTRIBUTES",     0x00000502UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_SUPPORTED_CMS_ATTRIBUTES",   0x00000503UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_ALLOWED_MECHANISMS",         (CKF_ARRAY_ATTRIBUTE|0x00000600UL), CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_PROFILE_ID",                 0x00000601UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_BAG",              0x00000602UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_BAGSIZE",          0x00000603UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_BOBS1STMSG",       0x00000604UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_CKR",              0x00000605UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_CKS",              0x00000606UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_DHP",              0x00000607UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_DHR",              0x00000608UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_DHS",              0x00000609UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_HKR",              0x0000060aUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_HKS",              0x0000060bUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_ISALICE",          0x0000060cUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_NHKR",             0x0000060dUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_NHKS",             0x0000060eUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_NR",               0x0000060fUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_NS",               0x00000610UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_PNS",              0x00000611UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_X2RATCHET_RK",               0x00000612UL, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKA_VENDOR_DEFINED",             0x80000000UL, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_DATA",                       0x00000000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_CERTIFICATE",                0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_PUBLIC_KEY",                 0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_PRIVATE_KEY",                0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_SECRET_KEY",                 0x00000004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_HW_FEATURE",                 0x00000005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_DOMAIN_PARAMETERS",          0x00000006UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_MECHANISM",                  0x00000007UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_OTP_KEY",                    0x00000008UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKO_VENDOR_DEFINED",             0x80000000UL, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_RSA",                        0x00000000UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_DSA",                        0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_DH",                         0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_ECDSA",                      0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_EC",                         0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_X9_42_DH",                   0x00000004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_KEA",                        0x00000005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_GENERIC_SECRET",             0x00000010UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_RC2",                        0x00000011UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_RC4",                        0x00000012UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_DES",                        0x00000013UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_DES2",                       0x00000014UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_DES3",                       0x00000015UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_CAST",                       0x00000016UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_CAST3",                      0x00000017UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_CAST5",                      0x00000018UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_CAST128",                    0x00000018UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_RC5",                        0x00000019UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_IDEA",                       0x0000001AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SKIPJACK",                   0x0000001BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_BATON",                      0x0000001CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_JUNIPER",                    0x0000001DUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_CDMF",                       0x0000001EUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_AES",                        0x0000001FUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_BLOWFISH",                   0x00000020UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_TWOFISH",                    0x00000021UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SECURID",                    0x00000022UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_HOTP",                       0x00000023UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_ACTI",                       0x00000024UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_CAMELLIA",                   0x00000025UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_ARIA",                       0x00000026UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_MD5_HMAC",                   0x00000027UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA_1_HMAC",                 0x00000028UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_RIPEMD128_HMAC",             0x00000029UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_RIPEMD160_HMAC",             0x0000002AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA256_HMAC",                0x0000002BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA384_HMAC",                0x0000002CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA512_HMAC",                0x0000002DUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA224_HMAC",                0x0000002EUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SEED",                       0x0000002FUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_GOSTR3410",                  0x00000030UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_GOSTR3411",                  0x00000031UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_GOST28147",                  0x00000032UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_CHACHA20",                   0x00000033UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_POLY1305",                   0x00000034UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_AES_XTS",                    0x00000035UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA3_224_HMAC",              0x00000036UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA3_256_HMAC",              0x00000037UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA3_384_HMAC",              0x00000038UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA3_512_HMAC",              0x00000039UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_BLAKE2B_160_HMAC",           0x0000003aUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_BLAKE2B_256_HMAC",           0x0000003bUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_BLAKE2B_384_HMAC",           0x0000003cUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_BLAKE2B_512_HMAC",           0x0000003dUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SALSA20",                    0x0000003eUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_X2RATCHET",                  0x0000003fUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_EC_EDWARDS",                 0x00000040UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_EC_MONTGOMERY",              0x00000041UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_HKDF",                       0x00000042UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA512_224_HMAC",            0x00000043UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA512_256_HMAC",            0x00000044UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_SHA512_T_HMAC",              0x00000045UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKK_VENDOR_DEFINED",             0x80000000UL, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA1",                  0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA256",                0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA384",                0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA512",                0x00000004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA224",                0x00000005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA3_224",              0x00000006UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA3_256",              0x00000007UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA3_384",              0x00000008UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKG_MGF1_SHA3_512",              0x00000009UL, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKZ_DATA_SPECIFIED",             0x00000001UL, CONST_CS | CONST_PERSISTENT);

    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_NULL",                       0x00000001UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA1_KDF",                   0x00000002UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA1_KDF_ASN1",              0x00000003UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA1_KDF_CONCATENATE",       0x00000004UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA224_KDF",                 0x00000005UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA256_KDF",                 0x00000006UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA384_KDF",                 0x00000007UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA512_KDF",                 0x00000008UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_CPDIVERSIFY_KDF",            0x00000009UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_224_KDF",               0x0000000AUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_256_KDF",               0x0000000BUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_384_KDF",               0x0000000CUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_512_KDF",               0x0000000DUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA1_KDF_SP800",             0x0000000EUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA224_KDF_SP800",           0x0000000FUL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA256_KDF_SP800",           0x00000010UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA384_KDF_SP800",           0x00000011UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA512_KDF_SP800",           0x00000012UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_224_KDF_SP800",         0x00000013UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_256_KDF_SP800",         0x00000014UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_384_KDF_SP800",         0x00000015UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_SHA3_512_KDF_SP800",         0x00000016UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_BLAKE2B_160_KDF",            0x00000017UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_BLAKE2B_256_KDF",            0x00000018UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_BLAKE2B_384_KDF",            0x00000019UL, CONST_CS | CONST_PERSISTENT);
    REGISTER_NS_LONG_CONSTANT("Pkcs11", "CKD_BLAKE2B_512_KDF",            0x0000001aUL, CONST_CS | CONST_PERSISTENT);

    return SUCCESS;
}


PHP_MINFO_FUNCTION(pkcs11)
{
    php_info_print_table_start();
    php_info_print_table_header(2, "PKCS#11 support", "enabled");
    php_info_print_table_end();
}

zend_module_entry pkcs11_module_entry = {
    STANDARD_MODULE_HEADER,
    PHP_PKCS11_NAME,
    NULL,                           /* zend_function_entry */
    PHP_MINIT(pkcs11),              /* PHP_MINIT - Module initialization */
    NULL,                           /* PHP_MSHUTDOWN - Module shutdown */
    NULL,                           /* PHP_RINIT - Request initialization */
    NULL,                           /* PHP_RSHUTDOWN - Request shutdown */
    PHP_MINFO(pkcs11),              /* PHP_MINFO - Module info */
    PHP_PKCS11_VERSION,             /* Version */
    STANDARD_MODULE_PROPERTIES
};

#ifdef COMPILE_DL_PKCS11
# ifdef ZTS
ZEND_TSRMLS_CACHE_DEFINE()
# endif
ZEND_GET_MODULE(pkcs11)
#endif
